// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "MatchService.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using namespace  ::match_service;

class MatchServiceHandler : virtual public MatchServiceIf {
 public:
  MatchServiceHandler() {
    // Your initialization goes here
  }

  int32_t addUser(const User& user, const std::string& info) {
    // Your implementation goes here
    printf("addUser\n");
  }

  int32_t deleteUser(const User& user, const std::string& info) {
    // Your implementation goes here
    printf("deleteUser\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  ::std::shared_ptr<MatchServiceHandler> handler(new MatchServiceHandler());
  ::std::shared_ptr<TProcessor> processor(new MatchServiceProcessor(handler));
  ::std::shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  ::std::shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  ::std::shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

