/**
 * Autogenerated by Thrift Compiler (0.23.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef MatchService_H
#define MatchService_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include <memory>
#include "match_types.h"

namespace match_service {

#ifdef _MSC_VER
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class MatchServiceIf {
 public:
  virtual ~MatchServiceIf() {}
  virtual int32_t addUser(const User& user, const std::string& info) = 0;
  virtual int32_t deleteUser(const User& user, const std::string& info) = 0;
};

class MatchServiceIfFactory {
 public:
  typedef MatchServiceIf Handler;

  virtual ~MatchServiceIfFactory() {}

  virtual MatchServiceIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(MatchServiceIf* /* handler */) = 0;
  };

class MatchServiceIfSingletonFactory : virtual public MatchServiceIfFactory {
 public:
  MatchServiceIfSingletonFactory(const ::std::shared_ptr<MatchServiceIf>& iface) : iface_(iface) {}
  virtual ~MatchServiceIfSingletonFactory() {}

  virtual MatchServiceIf* getHandler(const ::apache::thrift::TConnectionInfo&) override {
    return iface_.get();
  }
  virtual void releaseHandler(MatchServiceIf* /* handler */) override {}

 protected:
  ::std::shared_ptr<MatchServiceIf> iface_;
};

class MatchServiceNull : virtual public MatchServiceIf {
 public:
  virtual ~MatchServiceNull() {}
  int32_t addUser(const User& /* user */, const std::string& /* info */) override {
    int32_t _return = 0;
    return _return;
  }
  int32_t deleteUser(const User& /* user */, const std::string& /* info */) override {
    int32_t _return = 0;
    return _return;
  }
};

typedef struct _MatchService_addUser_args__isset {
  _MatchService_addUser_args__isset() : user(false), info(false) {}
  bool user :1;
  bool info :1;
} _MatchService_addUser_args__isset;

class MatchService_addUser_args {
 public:

  MatchService_addUser_args(const MatchService_addUser_args&);
  MatchService_addUser_args& operator=(const MatchService_addUser_args&);
  MatchService_addUser_args() noexcept;

  virtual ~MatchService_addUser_args() noexcept;
  User user;
  std::string info;

  _MatchService_addUser_args__isset __isset;

  void __set_user(const User& val);

  void __set_info(const std::string& val);

  bool operator == (const MatchService_addUser_args & rhs) const;
  bool operator != (const MatchService_addUser_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const MatchService_addUser_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class MatchService_addUser_pargs {
 public:


  virtual ~MatchService_addUser_pargs() noexcept;
  const User* user;
  const std::string* info;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _MatchService_addUser_result__isset {
  _MatchService_addUser_result__isset() : success(false) {}
  bool success :1;
} _MatchService_addUser_result__isset;

class MatchService_addUser_result {
 public:

  MatchService_addUser_result(const MatchService_addUser_result&) noexcept;
  MatchService_addUser_result& operator=(const MatchService_addUser_result&) noexcept;
  MatchService_addUser_result() noexcept;

  virtual ~MatchService_addUser_result() noexcept;
  int32_t success;

  _MatchService_addUser_result__isset __isset;

  void __set_success(const int32_t val);

  bool operator == (const MatchService_addUser_result & rhs) const;
  bool operator != (const MatchService_addUser_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const MatchService_addUser_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _MatchService_addUser_presult__isset {
  _MatchService_addUser_presult__isset() : success(false) {}
  bool success :1;
} _MatchService_addUser_presult__isset;

class MatchService_addUser_presult {
 public:


  virtual ~MatchService_addUser_presult() noexcept;
  int32_t* success;

  _MatchService_addUser_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _MatchService_deleteUser_args__isset {
  _MatchService_deleteUser_args__isset() : user(false), info(false) {}
  bool user :1;
  bool info :1;
} _MatchService_deleteUser_args__isset;

class MatchService_deleteUser_args {
 public:

  MatchService_deleteUser_args(const MatchService_deleteUser_args&);
  MatchService_deleteUser_args& operator=(const MatchService_deleteUser_args&);
  MatchService_deleteUser_args() noexcept;

  virtual ~MatchService_deleteUser_args() noexcept;
  User user;
  std::string info;

  _MatchService_deleteUser_args__isset __isset;

  void __set_user(const User& val);

  void __set_info(const std::string& val);

  bool operator == (const MatchService_deleteUser_args & rhs) const;
  bool operator != (const MatchService_deleteUser_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const MatchService_deleteUser_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class MatchService_deleteUser_pargs {
 public:


  virtual ~MatchService_deleteUser_pargs() noexcept;
  const User* user;
  const std::string* info;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _MatchService_deleteUser_result__isset {
  _MatchService_deleteUser_result__isset() : success(false) {}
  bool success :1;
} _MatchService_deleteUser_result__isset;

class MatchService_deleteUser_result {
 public:

  MatchService_deleteUser_result(const MatchService_deleteUser_result&) noexcept;
  MatchService_deleteUser_result& operator=(const MatchService_deleteUser_result&) noexcept;
  MatchService_deleteUser_result() noexcept;

  virtual ~MatchService_deleteUser_result() noexcept;
  int32_t success;

  _MatchService_deleteUser_result__isset __isset;

  void __set_success(const int32_t val);

  bool operator == (const MatchService_deleteUser_result & rhs) const;
  bool operator != (const MatchService_deleteUser_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const MatchService_deleteUser_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _MatchService_deleteUser_presult__isset {
  _MatchService_deleteUser_presult__isset() : success(false) {}
  bool success :1;
} _MatchService_deleteUser_presult__isset;

class MatchService_deleteUser_presult {
 public:


  virtual ~MatchService_deleteUser_presult() noexcept;
  int32_t* success;

  _MatchService_deleteUser_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class MatchServiceClient : virtual public MatchServiceIf {
 public:
  MatchServiceClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  MatchServiceClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  int32_t addUser(const User& user, const std::string& info) override;
  void send_addUser(const User& user, const std::string& info);
  int32_t recv_addUser();
  int32_t deleteUser(const User& user, const std::string& info) override;
  void send_deleteUser(const User& user, const std::string& info);
  int32_t recv_deleteUser();
 protected:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class MatchServiceProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  ::std::shared_ptr<MatchServiceIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext) override;
 private:
  typedef  void (MatchServiceProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_addUser(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_deleteUser(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  MatchServiceProcessor(::std::shared_ptr<MatchServiceIf> iface) :
    iface_(iface) {
    processMap_["addUser"] = &MatchServiceProcessor::process_addUser;
    processMap_["deleteUser"] = &MatchServiceProcessor::process_deleteUser;
  }

  virtual ~MatchServiceProcessor() {}
};

class MatchServiceProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  MatchServiceProcessorFactory(const ::std::shared_ptr< MatchServiceIfFactory >& handlerFactory) noexcept :
      handlerFactory_(handlerFactory) {}

  ::std::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo) override;

 protected:
  ::std::shared_ptr< MatchServiceIfFactory > handlerFactory_;
};

class MatchServiceMultiface : virtual public MatchServiceIf {
 public:
  MatchServiceMultiface(std::vector<std::shared_ptr<MatchServiceIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~MatchServiceMultiface() {}
 protected:
  std::vector<std::shared_ptr<MatchServiceIf> > ifaces_;
  MatchServiceMultiface() {}
  void add(::std::shared_ptr<MatchServiceIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  int32_t addUser(const User& user, const std::string& info) override {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->addUser(user, info);
    }
    return ifaces_[i]->addUser(user, info);
  }

  int32_t deleteUser(const User& user, const std::string& info) override {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->deleteUser(user, info);
    }
    return ifaces_[i]->deleteUser(user, info);
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class MatchServiceConcurrentClient : virtual public MatchServiceIf {
 public:
  MatchServiceConcurrentClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot, std::shared_ptr< ::apache::thrift::async::TConcurrentClientSyncInfo> sync) : sync_(sync)
{
    setProtocol(prot);
  }
  MatchServiceConcurrentClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot, std::shared_ptr< ::apache::thrift::async::TConcurrentClientSyncInfo> sync) : sync_(sync)
{
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  int32_t addUser(const User& user, const std::string& info) override;
  int32_t send_addUser(const User& user, const std::string& info);
  int32_t recv_addUser(const int32_t seqid);
  int32_t deleteUser(const User& user, const std::string& info) override;
  int32_t send_deleteUser(const User& user, const std::string& info);
  int32_t recv_deleteUser(const int32_t seqid);
 protected:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  std::shared_ptr< ::apache::thrift::async::TConcurrentClientSyncInfo> sync_;
};

#ifdef _MSC_VER
  #pragma warning( pop )
#endif

} // namespace

#endif
