// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "gen-cpp/MatchService.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>
#include <thread>
#include <condition_variable>
#include <mutex>
#include <queue>
#include <vector>
#include <iostream>
#include <string>
#include <thread>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using namespace  ::match_service;

// 结构体:Task 属性：User,op(string)操作类型：addUser,deleteUser
struct Task {
  User user;
  std::string op;
};

// 结构体：Message_que 全局对象：message_que
// 属性：Task队列 + 互斥信号量 + 条件变量
struct Message_que {
  std::queue<Task> que;
  std::mutex mutex;
  std::condition_variable cv;
};
Message_que message_que;

//类：Pool 全局对象：pool
// 私有属性：User数组users 共有方法：增 删 匹配
class Pool{
  public:
  void addUser(User user){
    users.push_back(user);
  }
  void deleteUser(User user){
    for(int i = 0; i < users.size(); i++){
      if(users[i].id == user.id){
        users.erase(users.begin() + i);
        break;
      }
    }
  }
  void match(){
    if(users.size() < 2){
      return;
    }
    std::vector<User> match_users = users;
    users.clear();
    printf("match %d %d\n", match_users[0].id, match_users[1].id);
  }
  private:
  std::vector<User> users;
};
Pool pool;



class MatchServiceHandler : virtual public MatchServiceIf {
 public:
  MatchServiceHandler() {
    // Your initialization goes here
  }

  int32_t addUser(const User& user, const std::string& info) {
    // Your implementation goes here
    printf("addUser\n");
    // 访问message_que队列，将任务添加到队列
    message_que.que.push({user, "addUser"});
    message_que.cv.notify_one();
    // 通知客户端任务已添加
    printf("addUser task added to message_que\n");
    return 0;
  }

  // 调用pool.match()进行匹配逻辑
  int32_t deleteUser(const User& user, const std::string& info) {
    // Your implementation goes here
    printf("deleteUser\n");
    // 访问message_que队列，将任务添加到队列
    message_que.que.push({user, "deleteUser"});
    message_que.cv.notify_one();
    // 通知客户端任务已添加
    printf("deleteUser task added to message_que\n");
    return 0;
  }
};

//函数：consume_task 功能：循环访问message_que队列
// 若队列为空，阻塞进程；否则，从队列中取出任务并处理 并根据操作类型（addUser,deleteUser）调用pool类的方法
void consume_task(){
  while(true){
    // 访问message_que队列，阻塞等待任务
    std::unique_lock<std::mutex> lock(message_que.mutex);
    message_que.cv.wait(lock, [&](){
      return !message_que.que.empty();
    });
    // 从队列中取出任务
    Task task = message_que.que.front();
    message_que.que.pop();
    // 根据操作类型调用pool类的方法
    if(task.op == "addUser"){
      pool.addUser(task.user);
    }else if(task.op == "deleteUser"){
      pool.deleteUser(task.user);
    }
    
    // 调用pool类的match方法
    pool.match();
  }
}

int main(int argc, char **argv) {
  int port = 9090;
  ::std::shared_ptr<MatchServiceHandler> handler(new MatchServiceHandler());
  ::std::shared_ptr<TProcessor> processor(new MatchServiceProcessor(handler));
  ::std::shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  ::std::shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  ::std::shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  
  // 为consume_task创建一个线程，用于处理任务队列中的任务
  std::thread consume_thread(consume_task);
  consume_thread.detach();    
  
  cout << "Welcome to MatchService server!" << endl;

  // 启动服务器
  server.serve();
  return 0;
}

